version: '3.8'

services:
  web:
    image: nginx:alpine
    ports:
      - "8081:80"
    networks:
      - webnet

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: your_database_name
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - webnet

  adminer:
    image: adminer
    ports:
      - "8082:8080"
    networks:
      - webnet

networks:
  webnet:

volumes:
  dbdata:
